"""create initial schema

Revision ID: 63bb6774ca47
Revises: 431e8c89119f
Create Date: 2026-09-13 20:01:46.871021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bb6774ca47'
down_revision: Union[str, Sequence[str], None] = '431e8c89119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmakers')),
    sa.UniqueConstraint('name', name=op.f('uq_bookmakers_name'))
    )
    op.create_table('countries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('confederation', sa.String(length=20), nullable=False),
    sa.CheckConstraint("confederation IN ('UEFA','CONMEBOL','CONCACAF','CAF','AFC','OFC')", name=op.f('ck_countries_confederation_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('iso3', name=op.f('uq_countries_iso3')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('feature_set_version', sa.String(length=20), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('metrics', sa.String(length=2000), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('train_end > train_start', name=op.f('ck_models_train_end_after_start')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_models_name_version'))
    )
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('rate_limit_ms', sa.Integer(), nullable=False),
    sa.Column('rate_limit_is_assumed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('competitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('confederation', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.CheckConstraint("format IN ('league','cup','group_knockout')", name=op.f('ck_competitions_format_valid')),
    sa.CheckConstraint("gender IN ('male','female')", name=op.f('ck_competitions_gender_valid')),
    sa.CheckConstraint("scope IN ('domestic','continental','international')", name=op.f('ck_competitions_scope_valid')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_competitions_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions'))
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('preferred_foot', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_players_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('referees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_referees_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referees'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('items_upserted', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('resume_point', sa.String(length=200), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.CheckConstraint("status <> 'partial' OR resume_point IS NOT NULL", name=op.f('ck_scrape_runs_partial_has_resume_point')),
    sa.CheckConstraint("status <> 'running' OR finished_at IS NULL", name=op.f('ck_scrape_runs_running_has_no_finish')),
    sa.CheckConstraint("status IN ('running','ok','failed','partial','abandoned')", name=op.f('ck_scrape_runs_status_valid')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at > started_at', name=op.f('ck_scrape_runs_finish_after_start')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_scrape_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index('ix_scrape_runs_one_running_per_source_target', 'scrape_runs', ['source_id', 'target'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('is_national_team', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_teams_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_venues_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('competition_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_sources_competition_id_competitions')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_competition_sources_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_sources')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_competition_sources_source_id_external_id'))
    )
    op.create_table('held_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scrape_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('held_kind', sa.String(length=20), nullable=False),
    sa.Column('published_value', sa.String(length=200), nullable=False),
    sa.Column('context', sa.String(length=500), nullable=True),
    sa.Column('candidates', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_ref', sa.BigInteger(), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status <> 'resolved' OR (resolved_ref IS NOT NULL AND resolved_at IS NOT NULL)) AND (status <> 'pending' OR (resolved_ref IS NULL AND resolved_at IS NULL))", name=op.f('ck_held_records_resolution_fields_match_status')),
    sa.CheckConstraint("held_kind IN ('team','match','player')", name=op.f('ck_held_records_held_kind_valid')),
    sa.CheckConstraint("status IN ('pending','resolved','discarded')", name=op.f('ck_held_records_status_valid')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_held_records_scrape_run_id_scrape_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_held_records_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_held_records'))
    )
    op.create_index('ix_held_records_unique_while_pending', 'held_records', ['source_id', 'held_kind', 'published_value'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('player_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.CheckConstraint("origin <> 'derived' OR reason = 'other'", name=op.f('ck_player_availability_derived_reason_is_other')),
    sa.CheckConstraint("origin IN ('reported','derived')", name=op.f('ck_player_availability_origin_valid')),
    sa.CheckConstraint("reason IN ('injury','suspension','international_duty','personal','other')", name=op.f('ck_player_availability_reason_valid')),
    sa.CheckConstraint("status IN ('out','doubtful')", name=op.f('ck_player_availability_status_valid')),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name=op.f('ck_player_availability_end_after_start')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_availability_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_availability_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_availability'))
    )
    op.create_table('player_team_spells',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name=op.f('ck_player_team_spells_end_after_start')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_team_spells_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_team_spells_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_team_spells'))
    )
    op.create_table('raw_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scrape_run_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_version', sa.String(length=20), nullable=True),
    sa.Column('parse_error', sa.String(length=2000), nullable=True),
    sa.CheckConstraint('parsed_at IS NULL OR reading_version IS NOT NULL', name=op.f('ck_raw_documents_parsed_requires_reading_version')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_raw_documents_scrape_run_id_scrape_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_documents')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_raw_documents_content_hash'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('num_teams', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date > start_date', name=op.f('ck_seasons_end_after_start')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_seasons_competition_id_competitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('competition_id', 'label', name=op.f('uq_seasons_competition_id_label'))
    )
    op.create_table('source_coverage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('statistic', sa.String(length=50), nullable=False),
    sa.Column('is_offered', sa.Boolean(), nullable=False),
    sa.Column('first_season', sa.String(length=20), nullable=True),
    sa.CheckConstraint('is_offered OR first_season IS NULL', name=op.f('ck_source_coverage_no_first_season_when_not_offered')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_source_coverage_competition_id_competitions')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_coverage_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_coverage')),
    sa.UniqueConstraint('source_id', 'competition_id', 'statistic', name=op.f('uq_source_coverage_source_id_competition_id_statistic'))
    )
    op.create_table('team_aliases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('normalized', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases')),
    sa.UniqueConstraint('team_id', 'normalized', name=op.f('uq_team_aliases_team_id_normalized'))
    )
    op.create_table('team_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('external_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_team_sources_source_id_sources')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_sources_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_sources')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_team_sources_source_id_external_id'))
    )
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=True),
    sa.Column('referee_id', sa.BigInteger(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('round', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('neutral_venue', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_ht', sa.Integer(), nullable=True),
    sa.Column('away_score_ht', sa.Integer(), nullable=True),
    sa.Column('home_score_et', sa.Integer(), nullable=True),
    sa.Column('away_score_et', sa.Integer(), nullable=True),
    sa.Column('home_pens', sa.Integer(), nullable=True),
    sa.Column('away_pens', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'finished' OR (home_score IS NOT NULL AND away_score IS NOT NULL)", name=op.f('ck_matches_finished_has_scores')),
    sa.CheckConstraint("status IN ('scheduled','live','finished','postponed','cancelled')", name=op.f('ck_matches_status_valid')),
    sa.CheckConstraint('(home_score_et IS NULL OR home_score IS NOT NULL) AND (away_score_et IS NULL OR away_score IS NOT NULL)', name=op.f('ck_matches_extra_time_requires_regular_time')),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_matches_home_away_different')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], name=op.f('fk_matches_referee_id_referees')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_matches_season_id_seasons')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_matches_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('season_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_season_teams_season_id_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_season_teams_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_teams')),
    sa.UniqueConstraint('season_id', 'team_id', name=op.f('uq_season_teams_season_id_team_id'))
    )
    op.create_table('lineups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_lineups_match_id_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_lineups_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_lineups_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineups')),
    sa.UniqueConstraint('match_id', 'player_id', name=op.f('uq_lineups_match_id_player_id'))
    )
    op.create_table('match_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('related_player_id', sa.BigInteger(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.CheckConstraint("event_type <> 'substitution' OR (player_id IS NOT NULL AND related_player_id IS NOT NULL)", name=op.f('ck_match_events_substitution_has_both_players')),
    sa.CheckConstraint("event_type IN ('goal','own_goal','penalty_scored','penalty_missed','yellow_card','red_card','substitution','var_review')", name=op.f('ck_match_events_event_type_valid')),
    sa.CheckConstraint('minute BETWEEN 0 AND 120', name=op.f('ck_match_events_minute_in_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_events_match_id_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_events_player_id_players')),
    sa.ForeignKeyConstraint(['related_player_id'], ['players.id'], name=op.f('fk_match_events_related_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_events_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_events'))
    )
    op.create_table('match_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=20), nullable=False),
    sa.Column('features', sa.String(length=4000), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('history_matches', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_features_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_features_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_features')),
    sa.UniqueConstraint('match_id', 'team_id', 'feature_set_version', 'as_of', name=op.f('uq_match_features_match_id_team_id_feature_set_version_as_of'))
    )
    op.create_table('match_odds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmaker_id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('selection', sa.String(length=20), nullable=False),
    sa.Column('line', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("market <> '1x2' OR line IS NULL", name=op.f('ck_match_odds_line_absent_for_1x2')),
    sa.CheckConstraint("market IN ('1x2','over_under','asian_handicap','btts')", name=op.f('ck_match_odds_market_valid')),
    sa.CheckConstraint("market NOT IN ('over_under','asian_handicap') OR line IS NOT NULL", name=op.f('ck_match_odds_line_required_for_totals_and_handicaps')),
    sa.CheckConstraint("selection IN ('home','draw','away','over','under','yes','no')", name=op.f('ck_match_odds_selection_valid')),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], name=op.f('fk_match_odds_bookmaker_id_bookmakers')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_odds_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_odds')),
    sa.UniqueConstraint('match_id', 'bookmaker_id', 'market', 'selection', 'line', 'recorded_at', name=op.f('uq_match_odds_match_id_bookmaker_id_market_selection_line_recorded_at'))
    )
    op.create_index('ix_match_odds_one_closing_per_selection', 'match_odds', ['match_id', 'bookmaker_id', 'market', 'selection'], unique=True, postgresql_where=sa.text('is_closing'))
    op.create_table('match_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_sources_match_id_matches')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_match_sources_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_sources')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_match_sources_source_id_external_id'))
    )
    op.create_table('match_team_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('xg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('xg_non_penalty', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shots_off_target', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('shots_inside_box', sa.Integer(), nullable=True),
    sa.Column('big_chances', sa.Integer(), nullable=True),
    sa.Column('big_chances_missed', sa.Integer(), nullable=True),
    sa.Column('woodwork', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('passes_completed', sa.Integer(), nullable=True),
    sa.Column('crosses', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('aerials_won', sa.Integer(), nullable=True),
    sa.CheckConstraint('passes_completed IS NULL OR passes IS NULL OR passes_completed <= passes', name=op.f('ck_match_team_stats_completed_passes_within_attempted')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_team_stats_match_id_matches')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_match_team_stats_source_id_sources')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_team_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_team_stats')),
    sa.UniqueConstraint('match_id', 'team_id', 'source_id', name=op.f('uq_match_team_stats_match_id_team_id_source_id'))
    )
    op.create_table('match_weather',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wind_kmh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_weather_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_weather')),
    sa.UniqueConstraint('match_id', name=op.f('uq_match_weather_match_id'))
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('xa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_player_match_stats_match_id_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_match_stats_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_match_stats')),
    sa.UniqueConstraint('match_id', 'player_id', name=op.f('uq_player_match_stats_match_id_player_id'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('p_home', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('p_draw', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('p_away', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('exp_goals_home', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('exp_goals_away', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('abs(p_home + p_draw + p_away - 1) < 0.000001', name=op.f('ck_predictions_probabilities_sum_to_one')),
    sa.CheckConstraint('p_away BETWEEN 0 AND 1', name=op.f('ck_predictions_p_away_in_range')),
    sa.CheckConstraint('p_draw BETWEEN 0 AND 1', name=op.f('ck_predictions_p_draw_in_range')),
    sa.CheckConstraint('p_home BETWEEN 0 AND 1', name=op.f('ck_predictions_p_home_in_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_predictions_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('match_id', 'model_id', 'as_of', name=op.f('uq_predictions_match_id_model_id_as_of'))
    )
    op.create_table('shots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('x', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('y', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('xg', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('body_part', sa.String(length=20), nullable=True),
    sa.Column('situation', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.CheckConstraint("result IN ('goal','saved','blocked','off_target','woodwork')", name=op.f('ck_shots_result_valid')),
    sa.CheckConstraint("situation IN ('open_play','corner','free_kick','penalty','set_piece')", name=op.f('ck_shots_situation_valid')),
    sa.CheckConstraint('minute BETWEEN 0 AND 120', name=op.f('ck_shots_minute_in_range')),
    sa.CheckConstraint('x BETWEEN 0 AND 1', name=op.f('ck_shots_x_in_range')),
    sa.CheckConstraint('xg BETWEEN 0 AND 1', name=op.f('ck_shots_xg_in_range')),
    sa.CheckConstraint('y BETWEEN 0 AND 1', name=op.f('ck_shots_y_in_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_shots_match_id_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_shots_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_shots_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_table('predictions')
    op.drop_table('player_match_stats')
    op.drop_table('match_weather')
    op.drop_table('match_team_stats')
    op.drop_table('match_sources')
    op.drop_index('ix_match_odds_one_closing_per_selection', table_name='match_odds', postgresql_where=sa.text('is_closing'))
    op.drop_table('match_odds')
    op.drop_table('match_features')
    op.drop_table('match_events')
    op.drop_table('lineups')
    op.drop_table('season_teams')
    op.drop_table('matches')
    op.drop_table('team_sources')
    op.drop_table('team_aliases')
    op.drop_table('source_coverage')
    op.drop_table('seasons')
    op.drop_table('raw_documents')
    op.drop_table('player_team_spells')
    op.drop_table('player_availability')
    op.drop_index('ix_held_records_unique_while_pending', table_name='held_records', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('held_records')
    op.drop_table('competition_sources')
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_index('ix_scrape_runs_one_running_per_source_target', table_name='scrape_runs', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('scrape_runs')
    op.drop_table('referees')
    op.drop_table('players')
    op.drop_table('competitions')
    op.drop_table('sources')
    op.drop_table('models')
    op.drop_table('countries')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
